// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: p10_pb.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace BLHX.Server.Common.Proto.p10
{

    [global::ProtoBuf.ProtoContract(Name = @"cs_10001")]
    public partial class Cs10001 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account", IsRequired = true)]
        public string Account { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"password", IsRequired = true)]
        public string Password { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"mail_box", IsRequired = true)]
        public string MailBox { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10018")]
    public partial class Cs10018 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"arg", IsRequired = true)]
        public uint Arg { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10020")]
    public partial class Cs10020 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"login_type", IsRequired = true)]
        public uint LoginType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"arg1", IsRequired = true)]
        public string Arg1 { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"arg2")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Arg2
        {
            get => __pbn__Arg2 ?? "";
            set => __pbn__Arg2 = value;
        }
        public bool ShouldSerializeArg2() => __pbn__Arg2 != null;
        public void ResetArg2() => __pbn__Arg2 = null;
        private string __pbn__Arg2;

        [global::ProtoBuf.ProtoMember(4, Name = @"arg3")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Arg3
        {
            get => __pbn__Arg3 ?? "";
            set => __pbn__Arg3 = value;
        }
        public bool ShouldSerializeArg3() => __pbn__Arg3 != null;
        public void ResetArg3() => __pbn__Arg3 = null;
        private string __pbn__Arg3;

        [global::ProtoBuf.ProtoMember(5, Name = @"arg4")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Arg4
        {
            get => __pbn__Arg4 ?? "";
            set => __pbn__Arg4 = value;
        }
        public bool ShouldSerializeArg4() => __pbn__Arg4 != null;
        public void ResetArg4() => __pbn__Arg4 = null;
        private string __pbn__Arg4;

        [global::ProtoBuf.ProtoMember(6, Name = @"check_key", IsRequired = true)]
        public string CheckKey { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"device")]
        public uint Device
        {
            get => __pbn__Device.GetValueOrDefault();
            set => __pbn__Device = value;
        }
        public bool ShouldSerializeDevice() => __pbn__Device != null;
        public void ResetDevice() => __pbn__Device = null;
        private uint? __pbn__Device;

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10022")]
    public partial class Cs10022 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account_id", IsRequired = true)]
        public uint AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"server_ticket", IsRequired = true)]
        public string ServerTicket { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"platform", IsRequired = true)]
        public string Platform { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"serverid", IsRequired = true)]
        public uint Serverid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"check_key", IsRequired = true)]
        public string CheckKey { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"device_id", IsRequired = true)]
        public string DeviceId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10024")]
    public partial class Cs10024 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nick_name", IsRequired = true)]
        public string NickName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"device_id", IsRequired = true)]
        public string DeviceId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10026")]
    public partial class Cs10026 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account_id", IsRequired = true)]
        public uint AccountId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10100")]
    public partial class Cs10100 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"need_request", IsRequired = true)]
        public uint NeedRequest { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10700")]
    public partial class Cs10700 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"platform", IsRequired = true)]
        public string Platform { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sub_platform", IsRequired = true)]
        public string SubPlatform { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"pack_index", IsRequired = true)]
        public uint PackIndex { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10800")]
    public partial class Cs10800 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state", IsRequired = true)]
        public uint State { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"platform", IsRequired = true)]
        public string Platform { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10802")]
    public partial class Cs10802 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state", IsRequired = true)]
        public uint State { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"platform", IsRequired = true)]
        public uint Platform { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10992")]
    public partial class Cs10992 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"track_type", IsRequired = true)]
        public uint TrackType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_id", IsRequired = true)]
        public uint EventId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"para1", IsRequired = true)]
        public string Para1 { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"para2", IsRequired = true)]
        public string Para2 { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"para3", IsRequired = true)]
        public string Para3 { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10993")]
    public partial class Cs10993 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"action_system", IsRequired = true)]
        public uint ActionSystem { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"action_id", IsRequired = true)]
        public uint ActionId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"action_des", IsRequired = true)]
        public string ActionDes { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"action_arg")]
        public uint ActionArg
        {
            get => __pbn__ActionArg.GetValueOrDefault();
            set => __pbn__ActionArg = value;
        }
        public bool ShouldSerializeActionArg() => __pbn__ActionArg != null;
        public void ResetActionArg() => __pbn__ActionArg = null;
        private uint? __pbn__ActionArg;

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10994")]
    public partial class Cs10994 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_10996")]
    public partial class Cs10996 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state", IsRequired = true)]
        public uint State { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"platform", IsRequired = true)]
        public string Platform { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"login_addr")]
    public partial class LoginAddr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"desc", IsRequired = true)]
        public string Desc { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ip", IsRequired = true)]
        public string Ip { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"port", IsRequired = true)]
        public uint Port { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"proxy_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProxyIp
        {
            get => __pbn__ProxyIp ?? "";
            set => __pbn__ProxyIp = value;
        }
        public bool ShouldSerializeProxyIp() => __pbn__ProxyIp != null;
        public void ResetProxyIp() => __pbn__ProxyIp = null;
        private string __pbn__ProxyIp;

        [global::ProtoBuf.ProtoMember(5, Name = @"proxy_port")]
        public uint ProxyPort
        {
            get => __pbn__ProxyPort.GetValueOrDefault();
            set => __pbn__ProxyPort = value;
        }
        public bool ShouldSerializeProxyPort() => __pbn__ProxyPort != null;
        public void ResetProxyPort() => __pbn__ProxyPort = null;
        private uint? __pbn__ProxyPort;

        [global::ProtoBuf.ProtoMember(6, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"noticeinfo")]
    public partial class Noticeinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"title", IsRequired = true)]
        public string Title { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content", IsRequired = true)]
        public string Content { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10002")]
    public partial class Sc10002 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10019")]
    public partial class Sc10019 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"serverlist")]
        public global::System.Collections.Generic.List<Serverinfo> Serverlists { get; set; } = new global::System.Collections.Generic.List<Serverinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10021")]
    public partial class Sc10021 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"serverlist")]
        public global::System.Collections.Generic.List<Serverinfo> Serverlists { get; set; } = new global::System.Collections.Generic.List<Serverinfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"account_id", IsRequired = true)]
        public uint AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"server_ticket", IsRequired = true)]
        public string ServerTicket { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"notice_list")]
        public global::System.Collections.Generic.List<Noticeinfo> NoticeLists { get; set; } = new global::System.Collections.Generic.List<Noticeinfo>();

        [global::ProtoBuf.ProtoMember(6, Name = @"device")]
        public uint Device
        {
            get => __pbn__Device.GetValueOrDefault();
            set => __pbn__Device = value;
        }
        public bool ShouldSerializeDevice() => __pbn__Device != null;
        public void ResetDevice() => __pbn__Device = null;
        private uint? __pbn__Device;

        [global::ProtoBuf.ProtoMember(7, Name = @"limit_server_ids")]
        public global::System.Collections.Generic.List<uint> LimitServerIds { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10023")]
    public partial class Sc10023 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user_id", IsRequired = true)]
        public uint UserId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"server_ticket", IsRequired = true)]
        public string ServerTicket { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"server_load")]
        public uint ServerLoad
        {
            get => __pbn__ServerLoad.GetValueOrDefault();
            set => __pbn__ServerLoad = value;
        }
        public bool ShouldSerializeServerLoad() => __pbn__ServerLoad != null;
        public void ResetServerLoad() => __pbn__ServerLoad = null;
        private uint? __pbn__ServerLoad;

        [global::ProtoBuf.ProtoMember(5, Name = @"db_load")]
        public uint DbLoad
        {
            get => __pbn__DbLoad.GetValueOrDefault();
            set => __pbn__DbLoad = value;
        }
        public bool ShouldSerializeDbLoad() => __pbn__DbLoad != null;
        public void ResetDbLoad() => __pbn__DbLoad = null;
        private uint? __pbn__DbLoad;

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10025")]
    public partial class Sc10025 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user_id", IsRequired = true)]
        public uint UserId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10027")]
    public partial class Sc10027 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user_id", IsRequired = true)]
        public uint UserId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level", IsRequired = true)]
        public uint Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10101")]
    public partial class Sc10101 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state", IsRequired = true)]
        public uint State { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10701")]
    public partial class Sc10701 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"url", IsRequired = true)]
        public string Url { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"version")]
        public global::System.Collections.Generic.List<string> Versions { get; set; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"addr_list")]
        public global::System.Collections.Generic.List<LoginAddr> AddrLists { get; set; } = new global::System.Collections.Generic.List<LoginAddr>();

        [global::ProtoBuf.ProtoMember(4, Name = @"timestamp", IsRequired = true)]
        public uint Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"monday_0oclock_timestamp", IsRequired = true)]
        public uint Monday0oclockTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"cdn_list")]
        public global::System.Collections.Generic.List<string> CdnLists { get; set; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10801")]
    public partial class Sc10801 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gateway_ip", IsRequired = true)]
        public string GatewayIp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"gateway_port", IsRequired = true)]
        public uint GatewayPort { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"url", IsRequired = true)]
        public string Url { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"version")]
        public global::System.Collections.Generic.List<string> Versions { get; set; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(5, Name = @"proxy_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProxyIp
        {
            get => __pbn__ProxyIp ?? "";
            set => __pbn__ProxyIp = value;
        }
        public bool ShouldSerializeProxyIp() => __pbn__ProxyIp != null;
        public void ResetProxyIp() => __pbn__ProxyIp = null;
        private string __pbn__ProxyIp;

        [global::ProtoBuf.ProtoMember(6, Name = @"proxy_port")]
        public uint ProxyPort
        {
            get => __pbn__ProxyPort.GetValueOrDefault();
            set => __pbn__ProxyPort = value;
        }
        public bool ShouldSerializeProxyPort() => __pbn__ProxyPort != null;
        public void ResetProxyPort() => __pbn__ProxyPort = null;
        private uint? __pbn__ProxyPort;

        [global::ProtoBuf.ProtoMember(7, Name = @"is_ts", IsRequired = true)]
        public uint IsTs { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"timestamp", IsRequired = true)]
        public uint Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"monday_0oclock_timestamp", IsRequired = true)]
        public uint Monday0oclockTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"cdn_list")]
        public global::System.Collections.Generic.List<string> CdnLists { get; set; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10803")]
    public partial class Sc10803 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gateway_ip", IsRequired = true)]
        public string GatewayIp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"gateway_port", IsRequired = true)]
        public uint GatewayPort { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"proxy_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProxyIp
        {
            get => __pbn__ProxyIp ?? "";
            set => __pbn__ProxyIp = value;
        }
        public bool ShouldSerializeProxyIp() => __pbn__ProxyIp != null;
        public void ResetProxyIp() => __pbn__ProxyIp = null;
        private string __pbn__ProxyIp;

        [global::ProtoBuf.ProtoMember(4, Name = @"proxy_port")]
        public uint ProxyPort
        {
            get => __pbn__ProxyPort.GetValueOrDefault();
            set => __pbn__ProxyPort = value;
        }
        public bool ShouldSerializeProxyPort() => __pbn__ProxyPort != null;
        public void ResetProxyPort() => __pbn__ProxyPort = null;
        private uint? __pbn__ProxyPort;

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10995")]
    public partial class Sc10995 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10997")]
    public partial class Sc10997 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version1", IsRequired = true)]
        public uint Version1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"version2", IsRequired = true)]
        public uint Version2 { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"version3", IsRequired = true)]
        public uint Version3 { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"version4", IsRequired = true)]
        public uint Version4 { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"gateway_ip", IsRequired = true)]
        public string GatewayIp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"gateway_port", IsRequired = true)]
        public uint GatewayPort { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"url", IsRequired = true)]
        public string Url { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10998")]
    public partial class Sc10998 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cmd", IsRequired = true)]
        public uint Cmd { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_10999")]
    public partial class Sc10999 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reason", IsRequired = true)]
        public uint Reason { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"serverinfo")]
    public partial class Serverinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ids")]
        public global::System.Collections.Generic.List<uint> Ids { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(2, Name = @"ip", IsRequired = true)]
        public string Ip { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"port", IsRequired = true)]
        public uint Port { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"state", IsRequired = true)]
        public uint State { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"tag_state")]
        public uint TagState
        {
            get => __pbn__TagState.GetValueOrDefault();
            set => __pbn__TagState = value;
        }
        public bool ShouldSerializeTagState() => __pbn__TagState != null;
        public void ResetTagState() => __pbn__TagState = null;
        private uint? __pbn__TagState;

        [global::ProtoBuf.ProtoMember(7, Name = @"sort")]
        public uint Sort
        {
            get => __pbn__Sort.GetValueOrDefault();
            set => __pbn__Sort = value;
        }
        public bool ShouldSerializeSort() => __pbn__Sort != null;
        public void ResetSort() => __pbn__Sort = null;
        private uint? __pbn__Sort;

        [global::ProtoBuf.ProtoMember(8, Name = @"proxy_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProxyIp
        {
            get => __pbn__ProxyIp ?? "";
            set => __pbn__ProxyIp = value;
        }
        public bool ShouldSerializeProxyIp() => __pbn__ProxyIp != null;
        public void ResetProxyIp() => __pbn__ProxyIp = null;
        private string __pbn__ProxyIp;

        [global::ProtoBuf.ProtoMember(9, Name = @"proxy_port")]
        public uint ProxyPort
        {
            get => __pbn__ProxyPort.GetValueOrDefault();
            set => __pbn__ProxyPort = value;
        }
        public bool ShouldSerializeProxyPort() => __pbn__ProxyPort != null;
        public void ResetProxyPort() => __pbn__ProxyPort = null;
        private uint? __pbn__ProxyPort;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
