// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: p19_pb.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace BLHX.Server.Common.Proto.p19
{

    [global::ProtoBuf.ProtoContract(Name = @"childinfo")]
    public partial class Childinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"x", IsRequired = true)]
        public uint X { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"y", IsRequired = true)]
        public uint Y { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19002")]
    public partial class Cs19002 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19004")]
    public partial class Cs19004 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19006")]
    public partial class Cs19006 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"furniture_id")]
        public global::System.Collections.Generic.List<uint> FurnitureIds { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(2, Name = @"currency", IsRequired = true)]
        public uint Currency { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19008")]
    public partial class Cs19008 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"floor", IsRequired = true)]
        public uint Floor { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"furniture_put_list")]
        public global::System.Collections.Generic.List<Furnitureputinfo> FurniturePutLists { get; set; } = new global::System.Collections.Generic.List<Furnitureputinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19011")]
    public partial class Cs19011 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19013")]
    public partial class Cs19013 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19015")]
    public partial class Cs19015 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_open", IsRequired = true)]
        public uint IsOpen { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19016")]
    public partial class Cs19016 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19018")]
    public partial class Cs19018 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19020")]
    public partial class Cs19020 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"furniture_put_list")]
        public global::System.Collections.Generic.List<Furnitureputinfo> FurniturePutLists { get; set; } = new global::System.Collections.Generic.List<Furnitureputinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19022")]
    public partial class Cs19022 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19024")]
    public partial class Cs19024 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19101")]
    public partial class Cs19101 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user_id", IsRequired = true)]
        public uint UserId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19103")]
    public partial class Cs19103 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"typ", IsRequired = true)]
        public int Typ { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19105")]
    public partial class Cs19105 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"typ", IsRequired = true)]
        public int Typ { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19107")]
    public partial class Cs19107 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"typ", IsRequired = true)]
        public int Typ { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19109")]
    public partial class Cs19109 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos", IsRequired = true)]
        public uint Pos { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"furniture_put_list")]
        public global::System.Collections.Generic.List<Furnitureputinfo> FurniturePutLists { get; set; } = new global::System.Collections.Generic.List<Furnitureputinfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"icon_image_md5", IsRequired = true)]
        public string IconImageMd5 { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"image_md5", IsRequired = true)]
        public string ImageMd5 { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19111")]
    public partial class Cs19111 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos", IsRequired = true)]
        public uint Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19113")]
    public partial class Cs19113 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"theme_id", IsRequired = true)]
        public string ThemeId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19115")]
    public partial class Cs19115 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"typ", IsRequired = true)]
        public int Typ { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19117")]
    public partial class Cs19117 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"typ", IsRequired = true)]
        public int Typ { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"page", IsRequired = true)]
        public int Page { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"num", IsRequired = true)]
        public int Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19119")]
    public partial class Cs19119 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"theme_id", IsRequired = true)]
        public string ThemeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"upload_time", IsRequired = true)]
        public uint UploadTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19121")]
    public partial class Cs19121 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"theme_id", IsRequired = true)]
        public string ThemeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"upload_time", IsRequired = true)]
        public uint UploadTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19123")]
    public partial class Cs19123 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos", IsRequired = true)]
        public uint Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19125")]
    public partial class Cs19125 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos", IsRequired = true)]
        public uint Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19127")]
    public partial class Cs19127 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"theme_id", IsRequired = true)]
        public string ThemeId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19129")]
    public partial class Cs19129 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target_id", IsRequired = true)]
        public uint TargetId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target_name", IsRequired = true)]
        public string TargetName { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"theme_id", IsRequired = true)]
        public string ThemeId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"theme_name", IsRequired = true)]
        public string ThemeName { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"reason", IsRequired = true)]
        public uint Reason { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_19131")]
    public partial class Cs19131 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id_list")]
        public global::System.Collections.Generic.List<string> IdLists { get; set; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"dormtheme")]
    public partial class Dormtheme : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"furniture_put_list")]
        public global::System.Collections.Generic.List<Furnitureputinfo> FurniturePutLists { get; set; } = new global::System.Collections.Generic.List<Furnitureputinfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"user_id", IsRequired = true)]
        public uint UserId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"pos", IsRequired = true)]
        public uint Pos { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"like_count", IsRequired = true)]
        public uint LikeCount { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"fav_count", IsRequired = true)]
        public uint FavCount { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"upload_time", IsRequired = true)]
        public uint UploadTime { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"icon_image_md5", IsRequired = true)]
        public string IconImageMd5 { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"image_md5", IsRequired = true)]
        public string ImageMd5 { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"dormtheme_profile")]
    public partial class DormthemeProfile : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"upload_time", IsRequired = true)]
        public uint UploadTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"furfloorputinfo")]
    public partial class Furfloorputinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"floor", IsRequired = true)]
        public uint Floor { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"furniture_put_list")]
        public global::System.Collections.Generic.List<Furnitureputinfo> FurniturePutLists { get; set; } = new global::System.Collections.Generic.List<Furnitureputinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"furnitureinfo")]
    public partial class Furnitureinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"get_time")]
        public uint GetTime
        {
            get => __pbn__GetTime.GetValueOrDefault();
            set => __pbn__GetTime = value;
        }
        public bool ShouldSerializeGetTime() => __pbn__GetTime != null;
        public void ResetGetTime() => __pbn__GetTime = null;
        private uint? __pbn__GetTime;

    }

    [global::ProtoBuf.ProtoContract(Name = @"furnitureputinfo")]
    public partial class Furnitureputinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"x", IsRequired = true)]
        public uint X { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"y", IsRequired = true)]
        public uint Y { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"dir", IsRequired = true)]
        public uint Dir { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"child")]
        public global::System.Collections.Generic.List<Childinfo> Childs { get; set; } = new global::System.Collections.Generic.List<Childinfo>();

        [global::ProtoBuf.ProtoMember(6, Name = @"parent", IsRequired = true)]
        public ulong Parent { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public uint shipId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"pop_info")]
    public partial class PopInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"intimacy", IsRequired = true)]
        public uint Intimacy { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"dorm_icon", IsRequired = true)]
        public uint DormIcon { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19001")]
    public partial class Sc19001 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lv", IsRequired = true)]
        public uint Lv { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"food", IsRequired = true)]
        public uint Food { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"food_max_increase", IsRequired = true)]
        public uint FoodMaxIncrease { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"food_max_increase_count", IsRequired = true)]
        public uint FoodMaxIncreaseCount { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"ship_id_list")]
        public global::System.Collections.Generic.List<uint> ShipIdLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(6, Name = @"furniture_id_list")]
        public global::System.Collections.Generic.List<Furnitureinfo> FurnitureIdLists { get; set; } = new global::System.Collections.Generic.List<Furnitureinfo>();

        [global::ProtoBuf.ProtoMember(7, Name = @"floor_num", IsRequired = true)]
        public uint FloorNum { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"exp_pos", IsRequired = true)]
        public uint ExpPos { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"furniture_put_list")]
        public global::System.Collections.Generic.List<Furfloorputinfo> FurniturePutLists { get; set; } = new global::System.Collections.Generic.List<Furfloorputinfo>();

        [global::ProtoBuf.ProtoMember(10, Name = @"next_timestamp", IsRequired = true)]
        public uint NextTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"load_exp", IsRequired = true)]
        public uint LoadExp { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"load_food", IsRequired = true)]
        public uint LoadFood { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"load_time", IsRequired = true)]
        public uint LoadTime { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19003")]
    public partial class Sc19003 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19005")]
    public partial class Sc19005 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exp", IsRequired = true)]
        public uint Exp { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19007")]
    public partial class Sc19007 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19009")]
    public partial class Sc19009 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"exp", IsRequired = true)]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"food_consume", IsRequired = true)]
        public uint FoodConsume { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19010")]
    public partial class Sc19010 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pop_list")]
        public global::System.Collections.Generic.List<PopInfo> PopLists { get; set; } = new global::System.Collections.Generic.List<PopInfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19012")]
    public partial class Sc19012 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19014")]
    public partial class Sc19014 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19017")]
    public partial class Sc19017 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19019")]
    public partial class Sc19019 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"theme_list")]
        public global::System.Collections.Generic.List<Dormtheme> ThemeLists { get; set; } = new global::System.Collections.Generic.List<Dormtheme>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19021")]
    public partial class Sc19021 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19023")]
    public partial class Sc19023 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19025")]
    public partial class Sc19025 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"furniture_put_list")]
        public global::System.Collections.Generic.List<Furfloorputinfo> FurniturePutLists { get; set; } = new global::System.Collections.Generic.List<Furfloorputinfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"visitor")]
        public Visitor Visitor { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19102")]
    public partial class Sc19102 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lv", IsRequired = true)]
        public uint Lv { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"food", IsRequired = true)]
        public uint Food { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"food_max_increase", IsRequired = true)]
        public uint FoodMaxIncrease { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"food_max_increase_count", IsRequired = true)]
        public uint FoodMaxIncreaseCount { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"ship_id_list")]
        public global::System.Collections.Generic.List<ShipInDrom> ShipIdLists { get; set; } = new global::System.Collections.Generic.List<ShipInDrom>();

        [global::ProtoBuf.ProtoMember(6, Name = @"furniture_id_list")]
        public global::System.Collections.Generic.List<Furnitureinfo> FurnitureIdLists { get; set; } = new global::System.Collections.Generic.List<Furnitureinfo>();

        [global::ProtoBuf.ProtoMember(7, Name = @"floor_num", IsRequired = true)]
        public uint FloorNum { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"exp_pos", IsRequired = true)]
        public uint ExpPos { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"furniture_put_list")]
        public global::System.Collections.Generic.List<Furfloorputinfo> FurniturePutLists { get; set; } = new global::System.Collections.Generic.List<Furfloorputinfo>();

        [global::ProtoBuf.ProtoMember(10, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19104")]
    public partial class Sc19104 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"access_id", IsRequired = true)]
        public string AccessId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"access_secret", IsRequired = true)]
        public string AccessSecret { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"expire_time", IsRequired = true)]
        public uint ExpireTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"security_token", IsRequired = true)]
        public string SecurityToken { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19106")]
    public partial class Sc19106 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"theme_list")]
        public global::System.Collections.Generic.List<Dormtheme> ThemeLists { get; set; } = new global::System.Collections.Generic.List<Dormtheme>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19108")]
    public partial class Sc19108 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"theme_list")]
        public global::System.Collections.Generic.List<Dormtheme> ThemeLists { get; set; } = new global::System.Collections.Generic.List<Dormtheme>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19110")]
    public partial class Sc19110 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19112")]
    public partial class Sc19112 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19114")]
    public partial class Sc19114 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"theme", IsRequired = true)]
        public Dormtheme Theme { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"has_fav", IsRequired = true)]
        public bool HasFav { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"has_like", IsRequired = true)]
        public bool HasLike { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19116")]
    public partial class Sc19116 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"theme_profile_list")]
        public global::System.Collections.Generic.List<DormthemeProfile> ThemeProfileLists { get; set; } = new global::System.Collections.Generic.List<DormthemeProfile>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19118")]
    public partial class Sc19118 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"theme_id_list")]
        public global::System.Collections.Generic.List<string> ThemeIdLists { get; set; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19120")]
    public partial class Sc19120 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19122")]
    public partial class Sc19122 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19124")]
    public partial class Sc19124 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19126")]
    public partial class Sc19126 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19128")]
    public partial class Sc19128 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19130")]
    public partial class Sc19130 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_19132")]
    public partial class Sc19132 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"list")]
        public global::System.Collections.Generic.List<ThemeMd5> Lists { get; set; } = new global::System.Collections.Generic.List<ThemeMd5>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"ship_in_drom")]
    public partial class ShipInDrom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tid", IsRequired = true)]
        public uint Tid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"state", IsRequired = true)]
        public uint State { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"skin_id", IsRequired = true)]
        public uint SkinId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"theme_md5")]
    public partial class ThemeMd5 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public string Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"md5", IsRequired = true)]
        public string Md5 { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"visitor")]
    public partial class Visitor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ship_template", IsRequired = true)]
        public uint ShipTemplate { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ship_skin", IsRequired = true)]
        public uint ShipSkin { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
