// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: p27_pb.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace BHXY.Server.Common.Proto.p27
{

    [global::ProtoBuf.ProtoContract(Name = @"child_attr")]
    public partial class ChildAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"val", IsRequired = true)]
        public uint Val { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_buff")]
    public partial class ChildBuff : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time", IsRequired = true)]
        public ChildTime Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_drop")]
    public partial class ChildDrop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"number", IsRequired = true)]
        public int Number { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_favor")]
    public partial class ChildFavor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lv", IsRequired = true)]
        public uint Lv { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exp", IsRequired = true)]
        public uint Exp { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_info")]
    public partial class ChildInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tid", IsRequired = true)]
        public uint Tid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cur_time", IsRequired = true)]
        public ChildTime CurTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"mood", IsRequired = true)]
        public uint Mood { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"money", IsRequired = true)]
        public uint Money { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"site_number", IsRequired = true)]
        public uint SiteNumber { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"attrs")]
        public global::System.Collections.Generic.List<ChildAttr> Attrs { get; set; } = new global::System.Collections.Generic.List<ChildAttr>();

        [global::ProtoBuf.ProtoMember(7, Name = @"favor", IsRequired = true)]
        public ChildFavor Favor { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"items")]
        public global::System.Collections.Generic.List<ChildItem> Items { get; set; } = new global::System.Collections.Generic.List<ChildItem>();

        [global::ProtoBuf.ProtoMember(9, Name = @"plan_history")]
        public global::System.Collections.Generic.List<ChildPlanHistory> PlanHistories { get; set; } = new global::System.Collections.Generic.List<ChildPlanHistory>();

        [global::ProtoBuf.ProtoMember(10, Name = @"memorys")]
        public global::System.Collections.Generic.List<uint> Memorys { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(11, Name = @"plans")]
        public global::System.Collections.Generic.List<ChildPlanCell> Plans { get; set; } = new global::System.Collections.Generic.List<ChildPlanCell>();

        [global::ProtoBuf.ProtoMember(12, Name = @"polaroids")]
        public global::System.Collections.Generic.List<ChildPolaroid> Polaroids { get; set; } = new global::System.Collections.Generic.List<ChildPolaroid>();

        [global::ProtoBuf.ProtoMember(13, Name = @"target", IsRequired = true)]
        public uint Target { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"tasks")]
        public global::System.Collections.Generic.List<ChildTask> Tasks { get; set; } = new global::System.Collections.Generic.List<ChildTask>();

        [global::ProtoBuf.ProtoMember(15, Name = @"realized_wish")]
        public global::System.Collections.Generic.List<uint> RealizedWishs { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(16, Name = @"buffs")]
        public global::System.Collections.Generic.List<ChildBuff> Buffs { get; set; } = new global::System.Collections.Generic.List<ChildBuff>();

        [global::ProtoBuf.ProtoMember(17, Name = @"user_name", IsRequired = true)]
        public string UserName { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"spec_events")]
        public global::System.Collections.Generic.List<uint> SpecEvents { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(19, Name = @"can_trigger_home_event", IsRequired = true)]
        public uint CanTriggerHomeEvent { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"home_events")]
        public global::System.Collections.Generic.List<uint> HomeEvents { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(21, Name = @"discount_event_id")]
        public global::System.Collections.Generic.List<uint> DiscountEventIds { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(22, Name = @"shop")]
        public global::System.Collections.Generic.List<ChildShopData> Shops { get; set; } = new global::System.Collections.Generic.List<ChildShopData>();

        [global::ProtoBuf.ProtoMember(23, Name = @"option_records")]
        public global::System.Collections.Generic.List<ChildOptionRecord> OptionRecords { get; set; } = new global::System.Collections.Generic.List<ChildOptionRecord>();

        [global::ProtoBuf.ProtoMember(24, Name = @"favor_award_history")]
        public global::System.Collections.Generic.List<uint> FavorAwardHistories { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(25, Name = @"is_ending", IsRequired = true)]
        public uint IsEnding { get; set; }

        [global::ProtoBuf.ProtoMember(26, Name = @"new_game_plus_count", IsRequired = true)]
        public uint NewGamePlusCount { get; set; }

        [global::ProtoBuf.ProtoMember(27, Name = @"had_target_stage_award", IsRequired = true)]
        public uint HadTargetStageAward { get; set; }

        [global::ProtoBuf.ProtoMember(28, Name = @"had_adjustment", IsRequired = true)]
        public uint HadAdjustment { get; set; }

        [global::ProtoBuf.ProtoMember(29, Name = @"is_special_secretary_valid", IsRequired = true)]
        public uint IsSpecialSecretaryValid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_item")]
    public partial class ChildItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num", IsRequired = true)]
        public uint Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_option_record")]
    public partial class ChildOptionRecord : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_plan_cell")]
    public partial class ChildPlanCell : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"day", IsRequired = true)]
        public uint Day { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"index", IsRequired = true)]
        public uint Index { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"value")]
        public global::System.Collections.Generic.List<ChildPlanVal> Values { get; set; } = new global::System.Collections.Generic.List<ChildPlanVal>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_plan_history")]
    public partial class ChildPlanHistory : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"plan_id", IsRequired = true)]
        public uint PlanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_plan_result")]
    public partial class ChildPlanResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"day", IsRequired = true)]
        public uint Day { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"index", IsRequired = true)]
        public uint Index { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"plan_drops")]
        public global::System.Collections.Generic.List<ChildDrop> PlanDrops { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

        [global::ProtoBuf.ProtoMember(4, Name = @"event_drops")]
        public global::System.Collections.Generic.List<ChildDrop> EventDrops { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

        [global::ProtoBuf.ProtoMember(5, Name = @"spec_event_drops")]
        public global::System.Collections.Generic.List<ChildDrop> SpecEventDrops { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_plan_val")]
    public partial class ChildPlanVal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"plan_id")]
        public uint PlanId
        {
            get => __pbn__PlanId.GetValueOrDefault();
            set => __pbn__PlanId = value;
        }
        public bool ShouldSerializePlanId() => __pbn__PlanId != null;
        public void ResetPlanId() => __pbn__PlanId = null;
        private uint? __pbn__PlanId;

        [global::ProtoBuf.ProtoMember(2, Name = @"event_id")]
        public uint EventId
        {
            get => __pbn__EventId.GetValueOrDefault();
            set => __pbn__EventId = value;
        }
        public bool ShouldSerializeEventId() => __pbn__EventId != null;
        public void ResetEventId() => __pbn__EventId = null;
        private uint? __pbn__EventId;

        [global::ProtoBuf.ProtoMember(3, Name = @"spec_event_id")]
        public uint SpecEventId
        {
            get => __pbn__SpecEventId.GetValueOrDefault();
            set => __pbn__SpecEventId = value;
        }
        public bool ShouldSerializeSpecEventId() => __pbn__SpecEventId != null;
        public void ResetSpecEventId() => __pbn__SpecEventId = null;
        private uint? __pbn__SpecEventId;

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_polaroid")]
    public partial class ChildPolaroid : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time", IsRequired = true)]
        public ChildTime Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_progress")]
    public partial class ChildProgress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"task_id", IsRequired = true)]
        public uint TaskId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"progress", IsRequired = true)]
        public uint Progress { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_shop_data")]
    public partial class ChildShopData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"shop_id", IsRequired = true)]
        public uint ShopId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"goods")]
        public global::System.Collections.Generic.List<ChildShopGoods> Goods { get; set; } = new global::System.Collections.Generic.List<ChildShopGoods>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_shop_goods")]
    public partial class ChildShopGoods : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num", IsRequired = true)]
        public uint Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_site_option")]
    public partial class ChildSiteOption : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"site_id", IsRequired = true)]
        public uint SiteId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"option_ids")]
        public global::System.Collections.Generic.List<uint> OptionIds { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_task")]
    public partial class ChildTask : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"progress", IsRequired = true)]
        public uint Progress { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"child_time")]
    public partial class ChildTime : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"month", IsRequired = true)]
        public uint Month { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"week", IsRequired = true)]
        public uint Week { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"day", IsRequired = true)]
        public uint Day { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27000")]
    public partial class Cs27000 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27002")]
    public partial class Cs27002 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27004")]
    public partial class Cs27004 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"siteid", IsRequired = true)]
        public uint Siteid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"optionid", IsRequired = true)]
        public uint Optionid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27006")]
    public partial class Cs27006 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27008")]
    public partial class Cs27008 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ending_id", IsRequired = true)]
        public uint EndingId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27010")]
    public partial class Cs27010 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27012")]
    public partial class Cs27012 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"plans")]
        public global::System.Collections.Generic.List<ChildPlanCell> Plans { get; set; } = new global::System.Collections.Generic.List<ChildPlanCell>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27014")]
    public partial class Cs27014 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27016")]
    public partial class Cs27016 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eventid", IsRequired = true)]
        public uint Eventid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27019")]
    public partial class Cs27019 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27023")]
    public partial class Cs27023 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"system", IsRequired = true)]
        public uint System { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27027")]
    public partial class Cs27027 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"spec_events_id", IsRequired = true)]
        public uint SpecEventsId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27029")]
    public partial class Cs27029 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27031")]
    public partial class Cs27031 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27033")]
    public partial class Cs27033 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"shop_id", IsRequired = true)]
        public uint ShopId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"goods")]
        public global::System.Collections.Generic.List<ChildShopGoods> Goods { get; set; } = new global::System.Collections.Generic.List<ChildShopGoods>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27035")]
    public partial class Cs27035 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27037")]
    public partial class Cs27037 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type_1", IsRequired = true)]
        public uint Type1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"progresses")]
        public global::System.Collections.Generic.List<ChildProgress> Progresses { get; set; } = new global::System.Collections.Generic.List<ChildProgress>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27039")]
    public partial class Cs27039 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"attr_id", IsRequired = true)]
        public uint AttrId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27041")]
    public partial class Cs27041 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ending_id", IsRequired = true)]
        public uint EndingId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27043")]
    public partial class Cs27043 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"shop_id", IsRequired = true)]
        public uint ShopId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27045")]
    public partial class Cs27045 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_27047")]
    public partial class Cs27047 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27001")]
    public partial class Sc27001 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"child", IsRequired = true)]
        public ChildInfo Child { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27003")]
    public partial class Sc27003 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"plan_results")]
        public global::System.Collections.Generic.List<ChildPlanResult> PlanResults { get; set; } = new global::System.Collections.Generic.List<ChildPlanResult>();

        [global::ProtoBuf.ProtoMember(3, Name = @"events")]
        public global::System.Collections.Generic.List<ChildPlanCell> Events { get; set; } = new global::System.Collections.Generic.List<ChildPlanCell>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27005")]
    public partial class Sc27005 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drops")]
        public global::System.Collections.Generic.List<ChildDrop> Drops { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

        [global::ProtoBuf.ProtoMember(3, Name = @"event_drops")]
        public global::System.Collections.Generic.List<ChildDrop> EventDrops { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

        [global::ProtoBuf.ProtoMember(4, Name = @"events")]
        public global::System.Collections.Generic.List<uint> Events { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(5, Name = @"branch_id", IsRequired = true)]
        public uint BranchId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27007")]
    public partial class Sc27007 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drops")]
        public global::System.Collections.Generic.List<ChildDrop> Drops { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27009")]
    public partial class Sc27009 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27011")]
    public partial class Sc27011 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"endings")]
        public global::System.Collections.Generic.List<uint> Endings { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27013")]
    public partial class Sc27013 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"plans")]
        public global::System.Collections.Generic.List<ChildPlanCell> Plans { get; set; } = new global::System.Collections.Generic.List<ChildPlanCell>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27015")]
    public partial class Sc27015 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"events")]
        public global::System.Collections.Generic.List<uint> Events { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27017")]
    public partial class Sc27017 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drops")]
        public global::System.Collections.Generic.List<ChildDrop> Drops { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27020")]
    public partial class Sc27020 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27021")]
    public partial class Sc27021 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tasks")]
        public global::System.Collections.Generic.List<ChildTask> Tasks { get; set; } = new global::System.Collections.Generic.List<ChildTask>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27022")]
    public partial class Sc27022 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ids")]
        public global::System.Collections.Generic.List<uint> Ids { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27024")]
    public partial class Sc27024 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"awards")]
        public global::System.Collections.Generic.List<ChildDrop> Awards { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27025")]
    public partial class Sc27025 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tasks")]
        public global::System.Collections.Generic.List<ChildTask> Tasks { get; set; } = new global::System.Collections.Generic.List<ChildTask>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27028")]
    public partial class Sc27028 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drops")]
        public global::System.Collections.Generic.List<ChildDrop> Drops { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27030")]
    public partial class Sc27030 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27032")]
    public partial class Sc27032 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27034")]
    public partial class Sc27034 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drops")]
        public global::System.Collections.Generic.List<ChildDrop> Drops { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27036")]
    public partial class Sc27036 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drops")]
        public global::System.Collections.Generic.List<ChildDrop> Drops { get; set; } = new global::System.Collections.Generic.List<ChildDrop>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27038")]
    public partial class Sc27038 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27040")]
    public partial class Sc27040 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27042")]
    public partial class Sc27042 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27044")]
    public partial class Sc27044 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"shop_data", IsRequired = true)]
        public ChildShopData ShopData { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27046")]
    public partial class Sc27046 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"opts")]
        public global::System.Collections.Generic.List<ChildSiteOption> Opts { get; set; } = new global::System.Collections.Generic.List<ChildSiteOption>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_27048")]
    public partial class Sc27048 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
