// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: p33_pb.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace BHXY.Server.Common.Proto.p33
{

    [global::ProtoBuf.ProtoContract(Name = @"ai_act")]
    public partial class AiAct : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ai_pos", IsRequired = true)]
        public Chaptercellpos AiPos { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"strategy_id")]
        public uint StrategyId
        {
            get => __pbn__StrategyId.GetValueOrDefault();
            set => __pbn__StrategyId = value;
        }
        public bool ShouldSerializeStrategyId() => __pbn__StrategyId != null;
        public void ResetStrategyId() => __pbn__StrategyId = null;
        private uint? __pbn__StrategyId;

        [global::ProtoBuf.ProtoMember(3, Name = @"target_pos")]
        public Chaptercellpos TargetPos { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"move_path")]
        public global::System.Collections.Generic.List<Chaptercellpos> MovePaths { get; set; } = new global::System.Collections.Generic.List<Chaptercellpos>();

        [global::ProtoBuf.ProtoMember(6, Name = @"ship_update")]
        public global::System.Collections.Generic.List<Shipinchapter> ShipUpdates { get; set; } = new global::System.Collections.Generic.List<Shipinchapter>();

        [global::ProtoBuf.ProtoMember(7, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"pos_list")]
        public global::System.Collections.Generic.List<Worldposinfo> PosLists { get; set; } = new global::System.Collections.Generic.List<Worldposinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"buff_info")]
    public partial class BuffInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"stack", IsRequired = true)]
        public uint Stack { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp", IsRequired = true)]
        public uint Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"round", IsRequired = true)]
        public uint Round { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"step", IsRequired = true)]
        public uint Step { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"chapterawardinfo")]
    public partial class Chapterawardinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"award", IsRequired = true)]
        public uint Award { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"flag", IsRequired = true)]
        public uint Flag { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"chaptercellinfo")]
    public partial class Chaptercellinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos", IsRequired = true)]
        public Chaptercellpos Pos { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"discovered")]
        public uint Discovered
        {
            get => __pbn__Discovered.GetValueOrDefault();
            set => __pbn__Discovered = value;
        }
        public bool ShouldSerializeDiscovered() => __pbn__Discovered != null;
        public void ResetDiscovered() => __pbn__Discovered = null;
        private uint? __pbn__Discovered;

    }

    [global::ProtoBuf.ProtoContract(Name = @"chaptercellpos")]
    public partial class Chaptercellpos : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"row", IsRequired = true)]
        public uint Row { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"column", IsRequired = true)]
        public uint Column { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cmdcollection")]
    public partial class Cmdcollection : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"progress", IsRequired = true)]
        public uint Progress { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"progress_list")]
        public global::System.Collections.Generic.List<uint> ProgressLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(3, Name = @"random_id", IsRequired = true)]
        public uint RandomId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"countinfo")]
    public partial class Countinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"step_count", IsRequired = true)]
        public uint StepCount { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"treasure_count", IsRequired = true)]
        public uint TreasureCount { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"task_progress", IsRequired = true)]
        public uint TaskProgress { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"activate_count", IsRequired = true)]
        public uint ActivateCount { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"collection_list")]
        public global::System.Collections.Generic.List<uint> CollectionLists { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33000")]
    public partial class Cs33000 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33101")]
    public partial class Cs33101 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"enter_map_id", IsRequired = true)]
        public uint EnterMapId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"elite_fleet_list")]
        public global::System.Collections.Generic.List<Elitefleetinfo> EliteFleetLists { get; set; } = new global::System.Collections.Generic.List<Elitefleetinfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"camp", IsRequired = true)]
        public uint Camp { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33103")]
    public partial class Cs33103 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"act", IsRequired = true)]
        public uint Act { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"group_id", IsRequired = true)]
        public uint GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"act_arg_1")]
        public uint ActArg1
        {
            get => __pbn__ActArg1.GetValueOrDefault();
            set => __pbn__ActArg1 = value;
        }
        public bool ShouldSerializeActArg1() => __pbn__ActArg1 != null;
        public void ResetActArg1() => __pbn__ActArg1 = null;
        private uint? __pbn__ActArg1;

        [global::ProtoBuf.ProtoMember(4, Name = @"act_arg_2")]
        public uint ActArg2
        {
            get => __pbn__ActArg2.GetValueOrDefault();
            set => __pbn__ActArg2 = value;
        }
        public bool ShouldSerializeActArg2() => __pbn__ActArg2 != null;
        public void ResetActArg2() => __pbn__ActArg2 = null;
        private uint? __pbn__ActArg2;

        [global::ProtoBuf.ProtoMember(5, Name = @"pos_list")]
        public global::System.Collections.Generic.List<Chaptercellpos> PosLists { get; set; } = new global::System.Collections.Generic.List<Chaptercellpos>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33106")]
    public partial class Cs33106 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33108")]
    public partial class Cs33108 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33110")]
    public partial class Cs33110 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data", IsRequired = true)]
        public uint Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33112")]
    public partial class Cs33112 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33205")]
    public partial class Cs33205 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint taskId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33207")]
    public partial class Cs33207 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint taskId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33301")]
    public partial class Cs33301 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"arg")]
        public global::System.Collections.Generic.List<uint> Args { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33401")]
    public partial class Cs33401 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"map_id", IsRequired = true)]
        public uint MapId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33403")]
    public partial class Cs33403 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"shop_id", IsRequired = true)]
        public uint ShopId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"shop_type", IsRequired = true)]
        public uint ShopType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33405")]
    public partial class Cs33405 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"fleet_list")]
        public global::System.Collections.Generic.List<FleetChange> FleetLists { get; set; } = new global::System.Collections.Generic.List<FleetChange>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33407")]
    public partial class Cs33407 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_list")]
        public global::System.Collections.Generic.List<uint> ShipLists { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33409")]
    public partial class Cs33409 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"elite_fleet_list")]
        public global::System.Collections.Generic.List<Elitefleetinfo> EliteFleetLists { get; set; } = new global::System.Collections.Generic.List<Elitefleetinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33413")]
    public partial class Cs33413 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33415")]
    public partial class Cs33415 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"task_list")]
        public global::System.Collections.Generic.List<uint> TaskLists { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33509")]
    public partial class Cs33509 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_33602")]
    public partial class Cs33602 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"list")]
        public global::System.Collections.Generic.List<WorldtargetFetch> Lists { get; set; } = new global::System.Collections.Generic.List<WorldtargetFetch>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"elitefleetinfo")]
    public partial class Elitefleetinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id_list")]
        public global::System.Collections.Generic.List<uint> ShipIdLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(2, Name = @"commanders")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Commandersinfo> Commanders { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Commandersinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"fleet_change")]
    public partial class FleetChange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id", IsRequired = true)]
        public uint GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ship_id")]
        public global::System.Collections.Generic.List<uint> ShipIds { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"goods_info")]
    public partial class GoodsInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"goods_id", IsRequired = true)]
        public uint GoodsId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"groupcmdcollection")]
    public partial class Groupcmdcollection : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id", IsRequired = true)]
        public uint GroupId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cmd_collection", IsRequired = true)]
        public Cmdcollection CmdCollection { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"groupinchapter")]
    public partial class Groupinchapter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ship_list")]
        public global::System.Collections.Generic.List<Shipinchapter> ShipLists { get; set; } = new global::System.Collections.Generic.List<Shipinchapter>();

        [global::ProtoBuf.ProtoMember(3, Name = @"pos", IsRequired = true)]
        public Chaptercellpos Pos { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"loss_flag", IsRequired = true)]
        public uint LossFlag { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"box_strategy_list")]
        public global::System.Collections.Generic.List<Strategyinfo> BoxStrategyLists { get; set; } = new global::System.Collections.Generic.List<Strategyinfo>();

        [global::ProtoBuf.ProtoMember(6, Name = @"ship_strategy_list")]
        public global::System.Collections.Generic.List<Strategyinfo> ShipStrategyLists { get; set; } = new global::System.Collections.Generic.List<Strategyinfo>();

        [global::ProtoBuf.ProtoMember(7, Name = @"strategy_ids")]
        public global::System.Collections.Generic.List<uint> StrategyIds { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(8, Name = @"bullet", IsRequired = true)]
        public uint Bullet { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"start_pos", IsRequired = true)]
        public Chaptercellpos StartPos { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"attach_list")]
        public global::System.Collections.Generic.List<uint> AttachLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(11, Name = @"damage_level", IsRequired = true)]
        public uint DamageLevel { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"buff_list")]
        public global::System.Collections.Generic.List<BuffInfo> BuffLists { get; set; } = new global::System.Collections.Generic.List<BuffInfo>();

        [global::ProtoBuf.ProtoMember(13, Name = @"commander_list")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Commandersinfo> CommanderLists { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Commandersinfo>();

        [global::ProtoBuf.ProtoMember(14, Name = @"kill_count", IsRequired = true)]
        public uint KillCount { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"cmd_collection")]
        public Cmdcollection CmdCollection { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"bullet_max", IsRequired = true)]
        public uint BulletMax { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"groupinfoupdate")]
    public partial class Groupinfoupdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"buff_list")]
        public global::System.Collections.Generic.List<BuffInfo> BuffLists { get; set; } = new global::System.Collections.Generic.List<BuffInfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"landinfo")]
    public partial class Landinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos", IsRequired = true)]
        public Chaptercellpos Pos { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"dir", IsRequired = true)]
        public Chaptercellpos Dir { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"distance", IsRequired = true)]
        public uint Distance { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"map_vision")]
    public partial class MapVision : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"map_id", IsRequired = true)]
        public uint MapId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"vision_list")]
        public global::System.Collections.Generic.List<Chaptercellpos> VisionLists { get; set; } = new global::System.Collections.Generic.List<Chaptercellpos>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"mapinfo")]
    public partial class Mapinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public Worldmapid Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cell_list")]
        public global::System.Collections.Generic.List<Chaptercellinfo> CellLists { get; set; } = new global::System.Collections.Generic.List<Chaptercellinfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"state_flag")]
        public global::System.Collections.Generic.List<uint> StateFlags { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(4, Name = @"land_list")]
        public global::System.Collections.Generic.List<Landinfo> LandLists { get; set; } = new global::System.Collections.Generic.List<Landinfo>();

        [global::ProtoBuf.ProtoMember(5, Name = @"pos_list")]
        public global::System.Collections.Generic.List<Worldposinfo> PosLists { get; set; } = new global::System.Collections.Generic.List<Worldposinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"port_info")]
    public partial class PortInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"port_id", IsRequired = true)]
        public uint PortId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"task_list")]
        public global::System.Collections.Generic.List<uint> TaskLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(3, Name = @"goods_list")]
        public global::System.Collections.Generic.List<GoodsInfo> GoodsLists { get; set; } = new global::System.Collections.Generic.List<GoodsInfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"next_refresh_time", IsRequired = true)]
        public uint NextRefreshTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33001")]
    public partial class Sc33001 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"world")]
        public Worldinfo World { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"is_world_open", IsRequired = true)]
        public uint IsWorldOpen { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"port_list")]
        public global::System.Collections.Generic.List<uint> PortLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(4, Name = @"camp", IsRequired = true)]
        public uint Camp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"target_list")]
        public global::System.Collections.Generic.List<Worldtarget> TargetLists { get; set; } = new global::System.Collections.Generic.List<Worldtarget>();

        [global::ProtoBuf.ProtoMember(6, Name = @"target_fetch_list")]
        public global::System.Collections.Generic.List<WorldtargetFetch> TargetFetchLists { get; set; } = new global::System.Collections.Generic.List<WorldtargetFetch>();

        [global::ProtoBuf.ProtoMember(7, Name = @"count_info", IsRequired = true)]
        public Countinfo CountInfo { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"out_shop_buy_list")]
        public global::System.Collections.Generic.List<GoodsInfo> OutShopBuyLists { get; set; } = new global::System.Collections.Generic.List<GoodsInfo>();

        [global::ProtoBuf.ProtoMember(9, Name = @"clean_chapter")]
        public global::System.Collections.Generic.List<uint> CleanChapters { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(10, Name = @"chapter_award")]
        public global::System.Collections.Generic.List<Chapterawardinfo> ChapterAwards { get; set; } = new global::System.Collections.Generic.List<Chapterawardinfo>();

        [global::ProtoBuf.ProtoMember(11, Name = @"fleet_list")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Fleetinfo> FleetLists { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Fleetinfo>();

        [global::ProtoBuf.ProtoMember(12, Name = @"new_flag_port_list")]
        public global::System.Collections.Generic.List<uint> NewFlagPortLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(13, Name = @"global_flag_list")]
        public global::System.Collections.Generic.List<uint> GlobalFlagLists { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33102")]
    public partial class Sc33102 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"world")]
        public Worldinfo World { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"chapter_award")]
        public global::System.Collections.Generic.List<Chapterawardinfo> ChapterAwards { get; set; } = new global::System.Collections.Generic.List<Chapterawardinfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"count_info", IsRequired = true)]
        public Countinfo CountInfo { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"port_list")]
        public global::System.Collections.Generic.List<uint> PortLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(6, Name = @"new_flag_port_list")]
        public global::System.Collections.Generic.List<uint> NewFlagPortLists { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33104")]
    public partial class Sc33104 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"move_path")]
        public global::System.Collections.Generic.List<Chaptercellpos> MovePaths { get; set; } = new global::System.Collections.Generic.List<Chaptercellpos>();

        [global::ProtoBuf.ProtoMember(3, Name = @"drop_list")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo> DropLists { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"enter_map_id")]
        public uint EnterMapId
        {
            get => __pbn__EnterMapId.GetValueOrDefault();
            set => __pbn__EnterMapId = value;
        }
        public bool ShouldSerializeEnterMapId() => __pbn__EnterMapId != null;
        public void ResetEnterMapId() => __pbn__EnterMapId = null;
        private uint? __pbn__EnterMapId;

        [global::ProtoBuf.ProtoMember(5, Name = @"ship_update")]
        public global::System.Collections.Generic.List<Shipinchapter> ShipUpdates { get; set; } = new global::System.Collections.Generic.List<Shipinchapter>();

        [global::ProtoBuf.ProtoMember(6, Name = @"ai_act_list")]
        public global::System.Collections.Generic.List<AiAct> AiActLists { get; set; } = new global::System.Collections.Generic.List<AiAct>();

        [global::ProtoBuf.ProtoMember(7, Name = @"id")]
        public Worldmapid Id { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"land_list")]
        public global::System.Collections.Generic.List<Landinfo> LandLists { get; set; } = new global::System.Collections.Generic.List<Landinfo>();

        [global::ProtoBuf.ProtoMember(9, Name = @"group_update")]
        public global::System.Collections.Generic.List<Groupinfoupdate> GroupUpdates { get; set; } = new global::System.Collections.Generic.List<Groupinfoupdate>();

        [global::ProtoBuf.ProtoMember(10, Name = @"event_id", IsRequired = true)]
        public uint EventId { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"pos_list")]
        public global::System.Collections.Generic.List<Worldposinfo> PosLists { get; set; } = new global::System.Collections.Generic.List<Worldposinfo>();

        [global::ProtoBuf.ProtoMember(12, Name = @"action_power")]
        public uint ActionPower
        {
            get => __pbn__ActionPower.GetValueOrDefault();
            set => __pbn__ActionPower = value;
        }
        public bool ShouldSerializeActionPower() => __pbn__ActionPower != null;
        public void ResetActionPower() => __pbn__ActionPower = null;
        private uint? __pbn__ActionPower;

        [global::ProtoBuf.ProtoMember(13, Name = @"action_power_extra")]
        public uint ActionPowerExtra
        {
            get => __pbn__ActionPowerExtra.GetValueOrDefault();
            set => __pbn__ActionPowerExtra = value;
        }
        public bool ShouldSerializeActionPowerExtra() => __pbn__ActionPowerExtra != null;
        public void ResetActionPowerExtra() => __pbn__ActionPowerExtra = null;
        private uint? __pbn__ActionPowerExtra;

        [global::ProtoBuf.ProtoMember(14, Name = @"target_list")]
        public global::System.Collections.Generic.List<Worldtarget> TargetLists { get; set; } = new global::System.Collections.Generic.List<Worldtarget>();

        [global::ProtoBuf.ProtoMember(15, Name = @"cmd_collection_list")]
        public global::System.Collections.Generic.List<Groupcmdcollection> CmdCollectionLists { get; set; } = new global::System.Collections.Generic.List<Groupcmdcollection>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33105")]
    public partial class Sc33105 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos_list")]
        public global::System.Collections.Generic.List<Worldposinfo> PosLists { get; set; } = new global::System.Collections.Generic.List<Worldposinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33107")]
    public partial class Sc33107 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"map")]
        public Mapinfo Map { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"is_reset")]
        public uint IsReset
        {
            get => __pbn__IsReset.GetValueOrDefault();
            set => __pbn__IsReset = value;
        }
        public bool ShouldSerializeIsReset() => __pbn__IsReset != null;
        public void ResetIsReset() => __pbn__IsReset = null;
        private uint? __pbn__IsReset;

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33109")]
    public partial class Sc33109 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33111")]
    public partial class Sc33111 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33113")]
    public partial class Sc33113 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drop_list")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo> DropLists { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"time", IsRequired = true)]
        public uint Time { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sairen_chapter")]
        public global::System.Collections.Generic.List<uint> SairenChapters { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33114")]
    public partial class Sc33114 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_world_open", IsRequired = true)]
        public uint IsWorldOpen { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ship_id_list")]
        public global::System.Collections.Generic.List<uint> ShipIdLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(3, Name = @"cmd_id_list")]
        public global::System.Collections.Generic.List<uint> CmdIdLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(4, Name = @"progress", IsRequired = true)]
        public uint Progress { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33202")]
    public partial class Sc33202 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"append_list")]
        public global::System.Collections.Generic.List<uint> AppendLists { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33203")]
    public partial class Sc33203 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"update_list")]
        public global::System.Collections.Generic.List<TaskInfo> UpdateLists { get; set; } = new global::System.Collections.Generic.List<TaskInfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33204")]
    public partial class Sc33204 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"delete_list")]
        public global::System.Collections.Generic.List<uint> DeleteLists { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33206")]
    public partial class Sc33206 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"task")]
        public TaskInfo Task { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33208")]
    public partial class Sc33208 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drops")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo> Drops { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"exp", IsRequired = true)]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"intimacy", IsRequired = true)]
        public uint Intimacy { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33302")]
    public partial class Sc33302 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drop_list")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo> DropLists { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33402")]
    public partial class Sc33402 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"port")]
        public PortInfo Port { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33404")]
    public partial class Sc33404 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drop_list")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo> DropLists { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33406")]
    public partial class Sc33406 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33408")]
    public partial class Sc33408 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33410")]
    public partial class Sc33410 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"group_list")]
        public global::System.Collections.Generic.List<Groupinchapter> GroupLists { get; set; } = new global::System.Collections.Generic.List<Groupinchapter>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33414")]
    public partial class Sc33414 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"task_list")]
        public global::System.Collections.Generic.List<uint> TaskLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(3, Name = @"next_refresh_time", IsRequired = true)]
        public uint NextRefreshTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33416")]
    public partial class Sc33416 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"task_list")]
        public global::System.Collections.Generic.List<TaskInfo> TaskLists { get; set; } = new global::System.Collections.Generic.List<TaskInfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33508")]
    public partial class Sc33508 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"boss_id", IsRequired = true)]
        public uint BossId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"hp", IsRequired = true)]
        public uint Hp { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33510")]
    public partial class Sc33510 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33601")]
    public partial class Sc33601 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target_list")]
        public global::System.Collections.Generic.List<Worldtarget> TargetLists { get; set; } = new global::System.Collections.Generic.List<Worldtarget>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_33603")]
    public partial class Sc33603 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drops")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo> Drops { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Dropinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"shipinchapter")]
    public partial class Shipinchapter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"hp_rant", IsRequired = true)]
        public uint HpRant { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"buff_list")]
        public global::System.Collections.Generic.List<BuffInfo> BuffLists { get; set; } = new global::System.Collections.Generic.List<BuffInfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"strategyinfo")]
    public partial class Strategyinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"task_info")]
    public partial class TaskInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"progress", IsRequired = true)]
        public uint Progress { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"accept_time", IsRequired = true)]
        public uint AcceptTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"submite_time", IsRequired = true)]
        public uint SubmiteTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"event_map_id", IsRequired = true)]
        public uint EventMapId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"world_item_info")]
    public partial class WorldItemInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"worldboss_info")]
    public partial class WorldbossInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"template_id", IsRequired = true)]
        public uint TemplateId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"lv", IsRequired = true)]
        public uint Lv { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"hp", IsRequired = true)]
        public uint Hp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"owner", IsRequired = true)]
        public uint Owner { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"last_time", IsRequired = true)]
        public uint LastTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"worldboss_rank")]
    public partial class WorldbossRank : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"damage", IsRequired = true)]
        public uint Damage { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"worldinfo")]
    public partial class Worldinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"map_id", IsRequired = true)]
        public uint MapId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        public uint Time
        {
            get => __pbn__Time.GetValueOrDefault();
            set => __pbn__Time = value;
        }
        public bool ShouldSerializeTime() => __pbn__Time != null;
        public void ResetTime() => __pbn__Time = null;
        private uint? __pbn__Time;

        [global::ProtoBuf.ProtoMember(3, Name = @"group_list")]
        public global::System.Collections.Generic.List<Groupinchapter> GroupLists { get; set; } = new global::System.Collections.Generic.List<Groupinchapter>();

        [global::ProtoBuf.ProtoMember(4, Name = @"round")]
        public uint Round
        {
            get => __pbn__Round.GetValueOrDefault();
            set => __pbn__Round = value;
        }
        public bool ShouldSerializeRound() => __pbn__Round != null;
        public void ResetRound() => __pbn__Round = null;
        private uint? __pbn__Round;

        [global::ProtoBuf.ProtoMember(5, Name = @"task_finish_count")]
        public uint TaskFinishCount
        {
            get => __pbn__TaskFinishCount.GetValueOrDefault();
            set => __pbn__TaskFinishCount = value;
        }
        public bool ShouldSerializeTaskFinishCount() => __pbn__TaskFinishCount != null;
        public void ResetTaskFinishCount() => __pbn__TaskFinishCount = null;
        private uint? __pbn__TaskFinishCount;

        [global::ProtoBuf.ProtoMember(6, Name = @"task_list")]
        public global::System.Collections.Generic.List<TaskInfo> TaskLists { get; set; } = new global::System.Collections.Generic.List<TaskInfo>();

        [global::ProtoBuf.ProtoMember(7, Name = @"submarine_state", IsRequired = true)]
        public uint SubmarineState { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"item_list")]
        public global::System.Collections.Generic.List<WorldItemInfo> ItemLists { get; set; } = new global::System.Collections.Generic.List<WorldItemInfo>();

        [global::ProtoBuf.ProtoMember(9, Name = @"goods_list")]
        public global::System.Collections.Generic.List<GoodsInfo> GoodsLists { get; set; } = new global::System.Collections.Generic.List<GoodsInfo>();

        [global::ProtoBuf.ProtoMember(11, Name = @"action_power", IsRequired = true)]
        public uint ActionPower { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"action_power_extra", IsRequired = true)]
        public uint ActionPowerExtra { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"last_recover_timestamp", IsRequired = true)]
        public uint LastRecoverTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"action_power_fetch_count", IsRequired = true)]
        public uint ActionPowerFetchCount { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"last_change_group_timestamp", IsRequired = true)]
        public uint LastChangeGroupTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"enter_map_id", IsRequired = true)]
        public uint EnterMapId { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"cd_list")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Idtimeinfo> CdLists { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Idtimeinfo>();

        [global::ProtoBuf.ProtoMember(18, Name = @"buff_list")]
        public global::System.Collections.Generic.List<BuffInfo> BuffLists { get; set; } = new global::System.Collections.Generic.List<BuffInfo>();

        [global::ProtoBuf.ProtoMember(19, Name = @"chapter_list")]
        public global::System.Collections.Generic.List<Worldmapid> ChapterLists { get; set; } = new global::System.Collections.Generic.List<Worldmapid>();

        [global::ProtoBuf.ProtoMember(20, Name = @"sairen_chapter")]
        public global::System.Collections.Generic.List<uint> SairenChapters { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(21, Name = @"month_boss")]
        public global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Kvdata> MonthBosses { get; set; } = new global::System.Collections.Generic.List<global::BHXY.Server.Common.Proto.common.Kvdata>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"worlditeminfo")]
    public partial class Worlditeminfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_type", IsRequired = true)]
        public uint ItemType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"item_id")]
        public uint ItemId
        {
            get => __pbn__ItemId.GetValueOrDefault();
            set => __pbn__ItemId = value;
        }
        public bool ShouldSerializeItemId() => __pbn__ItemId != null;
        public void ResetItemId() => __pbn__ItemId = null;
        private uint? __pbn__ItemId;

        [global::ProtoBuf.ProtoMember(3, Name = @"item_flag")]
        public uint ItemFlag
        {
            get => __pbn__ItemFlag.GetValueOrDefault();
            set => __pbn__ItemFlag = value;
        }
        public bool ShouldSerializeItemFlag() => __pbn__ItemFlag != null;
        public void ResetItemFlag() => __pbn__ItemFlag = null;
        private uint? __pbn__ItemFlag;

        [global::ProtoBuf.ProtoMember(4, Name = @"item_data")]
        public uint ItemData
        {
            get => __pbn__ItemData.GetValueOrDefault();
            set => __pbn__ItemData = value;
        }
        public bool ShouldSerializeItemData() => __pbn__ItemData != null;
        public void ResetItemData() => __pbn__ItemData = null;
        private uint? __pbn__ItemData;

        [global::ProtoBuf.ProtoMember(5, Name = @"buff_list")]
        public global::System.Collections.Generic.List<uint> BuffLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(6, Name = @"boss_hp")]
        public uint BossHp
        {
            get => __pbn__BossHp.GetValueOrDefault();
            set => __pbn__BossHp = value;
        }
        public bool ShouldSerializeBossHp() => __pbn__BossHp != null;
        public void ResetBossHp() => __pbn__BossHp = null;
        private uint? __pbn__BossHp;

        [global::ProtoBuf.ProtoMember(7, Name = @"effect_list")]
        public global::System.Collections.Generic.List<uint> EffectLists { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"worldmapid")]
    public partial class Worldmapid : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"random_id", IsRequired = true)]
        public uint RandomId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"template_id", IsRequired = true)]
        public uint TemplateId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"worldposinfo")]
    public partial class Worldposinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos", IsRequired = true)]
        public Chaptercellpos Pos { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"item_list")]
        public global::System.Collections.Generic.List<Worlditeminfo> ItemLists { get; set; } = new global::System.Collections.Generic.List<Worlditeminfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"worldtarget")]
    public partial class Worldtarget : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"process_list")]
        public global::System.Collections.Generic.List<WorldtargetProcess> ProcessLists { get; set; } = new global::System.Collections.Generic.List<WorldtargetProcess>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"worldtarget_fetch")]
    public partial class WorldtargetFetch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"star_list")]
        public global::System.Collections.Generic.List<uint> StarLists { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"worldtarget_process")]
    public partial class WorldtargetProcess : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"trigger_id", IsRequired = true)]
        public uint TriggerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
