// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: p40_pb.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace BLHX.Server.Common.Proto.p40
{

    [global::ProtoBuf.ProtoContract(Name = @"commander_exp")]
    public partial class CommanderExp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"commander_id", IsRequired = true)]
        public uint CommanderId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exp", IsRequired = true)]
        public uint Exp { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_40001")]
    public partial class Cs40001 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"system", IsRequired = true)]
        public uint System { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ship_id_list")]
        public global::System.Collections.Generic.List<uint> ShipIdLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(3, Name = @"data", IsRequired = true)]
        public uint Data { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"data2")]
        public global::System.Collections.Generic.List<uint> Data2s { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(5, Name = @"other_ship_id_list")]
        public global::System.Collections.Generic.List<Othershipid> OtherShipIdLists { get; set; } = new global::System.Collections.Generic.List<Othershipid>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_40003")]
    public partial class Cs40003 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"system", IsRequired = true)]
        public uint System { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data", IsRequired = true)]
        public uint Data { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"key", IsRequired = true)]
        public uint Key { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"score")]
        public uint Score
        {
            get => __pbn__Score.GetValueOrDefault();
            set => __pbn__Score = value;
        }
        public bool ShouldSerializeScore() => __pbn__Score != null;
        public void ResetScore() => __pbn__Score = null;
        private uint? __pbn__Score;

        [global::ProtoBuf.ProtoMember(5, Name = @"statistics")]
        public global::System.Collections.Generic.List<Statisticsinfo> Statistics { get; set; } = new global::System.Collections.Generic.List<Statisticsinfo>();

        [global::ProtoBuf.ProtoMember(6, Name = @"kill_id_list")]
        public global::System.Collections.Generic.List<uint> KillIdLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(7, Name = @"total_time", IsRequired = true)]
        public uint TotalTime { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"bot_percentage", IsRequired = true)]
        public uint BotPercentage { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"extra_param", IsRequired = true)]
        public uint ExtraParam { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"file_check")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FileCheck
        {
            get => __pbn__FileCheck ?? "";
            set => __pbn__FileCheck = value;
        }
        public bool ShouldSerializeFileCheck() => __pbn__FileCheck != null;
        public void ResetFileCheck() => __pbn__FileCheck = null;
        private string __pbn__FileCheck;

        [global::ProtoBuf.ProtoMember(11, Name = @"boss_hp")]
        public uint BossHp
        {
            get => __pbn__BossHp.GetValueOrDefault();
            set => __pbn__BossHp = value;
        }
        public bool ShouldSerializeBossHp() => __pbn__BossHp != null;
        public void ResetBossHp() => __pbn__BossHp = null;
        private uint? __pbn__BossHp;

        [global::ProtoBuf.ProtoMember(12, Name = @"enemy_info")]
        public global::System.Collections.Generic.List<Enemyinfo> EnemyInfoes { get; set; } = new global::System.Collections.Generic.List<Enemyinfo>();

        [global::ProtoBuf.ProtoMember(13, Name = @"data2")]
        public global::System.Collections.Generic.List<uint> Data2s { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(14, Name = @"commander_id_list")]
        public global::System.Collections.Generic.List<uint> CommanderIdLists { get; set; } = new global::System.Collections.Generic.List<uint>();

        [global::ProtoBuf.ProtoMember(15, Name = @"otherstatistics")]
        public global::System.Collections.Generic.List<Statisticsinfo> Otherstatistics { get; set; } = new global::System.Collections.Generic.List<Statisticsinfo>();

        [global::ProtoBuf.ProtoMember(16, Name = @"auto_before", IsRequired = true)]
        public uint AutoBefore { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"auto_switch_time", IsRequired = true)]
        public uint AutoSwitchTime { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"auto_after", IsRequired = true)]
        public uint AutoAfter { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_40005")]
    public partial class Cs40005 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"system", IsRequired = true)]
        public uint System { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_40007")]
    public partial class Cs40007 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"system", IsRequired = true)]
        public uint System { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"cnt", IsRequired = true)]
        public uint Cnt { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"dropperformance")]
    public partial class Dropperformance : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"enemy_id", IsRequired = true)]
        public uint EnemyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"resource_num", IsRequired = true)]
        public uint ResourceNum { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"other_num", IsRequired = true)]
        public uint OtherNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"enemyinfo")]
    public partial class Enemyinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"enemy_id", IsRequired = true)]
        public uint EnemyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"damage_taken", IsRequired = true)]
        public uint DamageTaken { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"total_hp", IsRequired = true)]
        public uint TotalHp { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"hpdropinfo")]
    public partial class Hpdropinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hp", IsRequired = true)]
        public uint Hp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drop_info")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> DropInfoes { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"othershipid")]
    public partial class Othershipid : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user_id", IsRequired = true)]
        public uint UserId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"quick_reward")]
    public partial class QuickReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"drop_list")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> DropLists { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_40002")]
    public partial class Sc40002 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"key")]
        public uint Key
        {
            get => __pbn__Key.GetValueOrDefault();
            set => __pbn__Key = value;
        }
        public bool ShouldSerializeKey() => __pbn__Key != null;
        public void ResetKey() => __pbn__Key = null;
        private uint? __pbn__Key;

        [global::ProtoBuf.ProtoMember(3, Name = @"drop_performance")]
        public global::System.Collections.Generic.List<Dropperformance> DropPerformances { get; set; } = new global::System.Collections.Generic.List<Dropperformance>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_40004")]
    public partial class Sc40004 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drop_info")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> DropInfoes { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"extra_drop_info")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> ExtraDropInfoes { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"player_exp", IsRequired = true)]
        public uint PlayerExp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"ship_exp_list")]
        public global::System.Collections.Generic.List<ShipExp> ShipExpLists { get; set; } = new global::System.Collections.Generic.List<ShipExp>();

        [global::ProtoBuf.ProtoMember(6, Name = @"mvp", IsRequired = true)]
        public uint Mvp { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"commander_exp")]
        public global::System.Collections.Generic.List<CommanderExp> CommanderExps { get; set; } = new global::System.Collections.Generic.List<CommanderExp>();

        [global::ProtoBuf.ProtoMember(8, Name = @"hp_drop_info")]
        public global::System.Collections.Generic.List<Hpdropinfo> HpDropInfoes { get; set; } = new global::System.Collections.Generic.List<Hpdropinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_40006")]
    public partial class Sc40006 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_40008")]
    public partial class Sc40008 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reward_list")]
        public global::System.Collections.Generic.List<QuickReward> RewardLists { get; set; } = new global::System.Collections.Generic.List<QuickReward>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_40009")]
    public partial class Sc40009 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"re40004")]
        public global::System.Collections.Generic.List<Sc40004> Re40004s { get; set; } = new global::System.Collections.Generic.List<Sc40004>();

        [global::ProtoBuf.ProtoMember(2, Name = @"system", IsRequired = true)]
        public uint System { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"arg1")]
        public uint Arg1
        {
            get => __pbn__Arg1.GetValueOrDefault();
            set => __pbn__Arg1 = value;
        }
        public bool ShouldSerializeArg1() => __pbn__Arg1 != null;
        public void ResetArg1() => __pbn__Arg1 = null;
        private uint? __pbn__Arg1;

    }

    [global::ProtoBuf.ProtoContract(Name = @"ship_exp")]
    public partial class ShipExp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exp", IsRequired = true)]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"intimacy", IsRequired = true)]
        public uint Intimacy { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"energy", IsRequired = true)]
        public uint Energy { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"statisticsinfo")]
    public partial class Statisticsinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"damage_cause", IsRequired = true)]
        public uint DamageCause { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"damage_caused", IsRequired = true)]
        public uint DamageCaused { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"hp_rest", IsRequired = true)]
        public uint HpRest { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"max_damage_once", IsRequired = true)]
        public uint MaxDamageOnce { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"ship_gear_score", IsRequired = true)]
        public uint ShipGearScore { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
