// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: p63_pb.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace BLHX.Server.Common.Proto.p63
{

    [global::ProtoBuf.ProtoContract(Name = @"bluprintinfo")]
    public partial class Bluprintinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"start_time", IsRequired = true)]
        public uint StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"blue_print_level", IsRequired = true)]
        public uint BluePrintLevel { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"exp", IsRequired = true)]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"start_duration")]
        public uint StartDuration
        {
            get => __pbn__StartDuration.GetValueOrDefault();
            set => __pbn__StartDuration = value;
        }
        public bool ShouldSerializeStartDuration() => __pbn__StartDuration != null;
        public void ResetStartDuration() => __pbn__StartDuration = null;
        private uint? __pbn__StartDuration;

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63001")]
    public partial class Cs63001 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tech_id", IsRequired = true)]
        public uint TechId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"refresh_id", IsRequired = true)]
        public uint RefreshId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63003")]
    public partial class Cs63003 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tech_id", IsRequired = true)]
        public uint TechId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"refresh_id", IsRequired = true)]
        public uint RefreshId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63005")]
    public partial class Cs63005 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tech_id", IsRequired = true)]
        public uint TechId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"refresh_id", IsRequired = true)]
        public uint RefreshId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63007")]
    public partial class Cs63007 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63009")]
    public partial class Cs63009 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target", IsRequired = true)]
        public uint Target { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63011")]
    public partial class Cs63011 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version", IsRequired = true)]
        public uint Version { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target", IsRequired = true)]
        public uint Target { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63013")]
    public partial class Cs63013 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tech_id", IsRequired = true)]
        public uint TechId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"refresh_id", IsRequired = true)]
        public uint RefreshId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63015")]
    public partial class Cs63015 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63200")]
    public partial class Cs63200 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"blueprint_id", IsRequired = true)]
        public uint BlueprintId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63202")]
    public partial class Cs63202 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"blueprint_id", IsRequired = true)]
        public uint BlueprintId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63204")]
    public partial class Cs63204 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63206")]
    public partial class Cs63206 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"blueprint_id", IsRequired = true)]
        public uint BlueprintId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63208")]
    public partial class Cs63208 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"blueprint_id", IsRequired = true)]
        public uint BlueprintId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63210")]
    public partial class Cs63210 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"blueprintid", IsRequired = true)]
        public uint Blueprintid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"itemid", IsRequired = true)]
        public uint Itemid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"number", IsRequired = true)]
        public uint Number { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"task_id", IsRequired = true)]
        public uint TaskId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63212")]
    public partial class Cs63212 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
        public uint Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63214")]
    public partial class Cs63214 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group", IsRequired = true)]
        public uint Group { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"itemid", IsRequired = true)]
        public uint Itemid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63301")]
    public partial class Cs63301 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"repair_id", IsRequired = true)]
        public uint RepairId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63303")]
    public partial class Cs63303 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63305")]
    public partial class Cs63305 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"meta_id", IsRequired = true)]
        public uint MetaId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63307")]
    public partial class Cs63307 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"skill_id", IsRequired = true)]
        public uint SkillId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63309")]
    public partial class Cs63309 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"skill_id", IsRequired = true)]
        public uint SkillId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63311")]
    public partial class Cs63311 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"skill_id", IsRequired = true)]
        public uint SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"index", IsRequired = true)]
        public uint Index { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63313")]
    public partial class Cs63313 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63317")]
    public partial class Cs63317 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id_list")]
        public global::System.Collections.Generic.List<uint> ShipIdLists { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"cs_63319")]
    public partial class Cs63319 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"skill_id", IsRequired = true)]
        public uint SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"books")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.ItemInfo> Books { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.ItemInfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"dr_number")]
    public partial class DrNumber : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"number", IsRequired = true)]
        public uint Number { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"finish_task")]
    public partial class FinishTask : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"skill_id", IsRequired = true)]
        public uint SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"task_id", IsRequired = true)]
        public uint TaskId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"finish_cnt", IsRequired = true)]
        public uint FinishCnt { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"meta_skill_simple_info")]
    public partial class MetaSkillSimpleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exp", IsRequired = true)]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"skill_id", IsRequired = true)]
        public uint SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"skill_exp")]
        public global::System.Collections.Generic.List<SkillExp> SkillExps { get; set; } = new global::System.Collections.Generic.List<SkillExp>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"metacharinfo")]
    public partial class Metacharinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"syn_rate", IsRequired = true)]
        public uint SynRate { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63000")]
    public partial class Sc63000 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"refresh_list")]
        public global::System.Collections.Generic.List<Technologyrefresh> RefreshLists { get; set; } = new global::System.Collections.Generic.List<Technologyrefresh>();

        [global::ProtoBuf.ProtoMember(2, Name = @"refresh_flag", IsRequired = true)]
        public uint RefreshFlag { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"catchup", IsRequired = true)]
        public Technologycatchup Catchup { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"queue")]
        public global::System.Collections.Generic.List<Technologyinfo> Queues { get; set; } = new global::System.Collections.Generic.List<Technologyinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63002")]
    public partial class Sc63002 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time", IsRequired = true)]
        public uint Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63004")]
    public partial class Sc63004 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"common_list")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> CommonLists { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"refresh_list")]
        public global::System.Collections.Generic.List<Technologyrefresh> RefreshLists { get; set; } = new global::System.Collections.Generic.List<Technologyrefresh>();

        [global::ProtoBuf.ProtoMember(4, Name = @"drop_list")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> DropLists { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(5, Name = @"catchup_list")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> CatchupLists { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(6, Name = @"catchupact_list")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> CatchupactLists { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63006")]
    public partial class Sc63006 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63008")]
    public partial class Sc63008 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"refresh_list")]
        public global::System.Collections.Generic.List<Technologyrefresh> RefreshLists { get; set; } = new global::System.Collections.Generic.List<Technologyrefresh>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63010")]
    public partial class Sc63010 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63012")]
    public partial class Sc63012 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63014")]
    public partial class Sc63014 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"refresh_list")]
        public global::System.Collections.Generic.List<Technologyrefresh> RefreshLists { get; set; } = new global::System.Collections.Generic.List<Technologyrefresh>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63016")]
    public partial class Sc63016 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drops")]
        public global::System.Collections.Generic.List<Technologydrop> Drops { get; set; } = new global::System.Collections.Generic.List<Technologydrop>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63100")]
    public partial class Sc63100 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"blueprint_list")]
        public global::System.Collections.Generic.List<Bluprintinfo> BlueprintLists { get; set; } = new global::System.Collections.Generic.List<Bluprintinfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"cold_time", IsRequired = true)]
        public uint ColdTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"daily_catchup_strengthen", IsRequired = true)]
        public uint DailyCatchupStrengthen { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"daily_catchup_strengthen_ur", IsRequired = true)]
        public uint DailyCatchupStrengthenUr { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63201")]
    public partial class Sc63201 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time", IsRequired = true)]
        public uint Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63203")]
    public partial class Sc63203 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ship")]
        public global::BLHX.Server.Common.Proto.common.Shipinfo Ship { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63205")]
    public partial class Sc63205 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63207")]
    public partial class Sc63207 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63209")]
    public partial class Sc63209 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63211")]
    public partial class Sc63211 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63213")]
    public partial class Sc63213 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63215")]
    public partial class Sc63215 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ship")]
        public global::BLHX.Server.Common.Proto.common.Shipinfo Ship { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63300")]
    public partial class Sc63300 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"meta_char_list")]
        public global::System.Collections.Generic.List<Metacharinfo> MetaCharLists { get; set; } = new global::System.Collections.Generic.List<Metacharinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63302")]
    public partial class Sc63302 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63304")]
    public partial class Sc63304 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63306")]
    public partial class Sc63306 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ship")]
        public global::BLHX.Server.Common.Proto.common.Shipinfo Ship { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63308")]
    public partial class Sc63308 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"switch_cnt", IsRequired = true)]
        public uint SwitchCnt { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63310")]
    public partial class Sc63310 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"switch_cnt", IsRequired = true)]
        public uint SwitchCnt { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63312")]
    public partial class Sc63312 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public uint Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63314")]
    public partial class Sc63314 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"double_exp", IsRequired = true)]
        public uint DoubleExp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"exp", IsRequired = true)]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"skill_id", IsRequired = true)]
        public uint SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"tasks")]
        public global::System.Collections.Generic.List<FinishTask> Tasks { get; set; } = new global::System.Collections.Generic.List<FinishTask>();

        [global::ProtoBuf.ProtoMember(6, Name = @"switch_cnt", IsRequired = true)]
        public uint SwitchCnt { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"skill_exp")]
        public global::System.Collections.Generic.List<SkillExp> SkillExps { get; set; } = new global::System.Collections.Generic.List<SkillExp>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63315")]
    public partial class Sc63315 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public uint Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"arg1")]
        public global::System.Collections.Generic.List<uint> Arg1s { get; set; } = new global::System.Collections.Generic.List<uint>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63316")]
    public partial class Sc63316 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"skill_info_list")]
        public global::System.Collections.Generic.List<SkillInfo> SkillInfoLists { get; set; } = new global::System.Collections.Generic.List<SkillInfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63318")]
    public partial class Sc63318 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"info_list")]
        public global::System.Collections.Generic.List<MetaSkillSimpleInfo> InfoLists { get; set; } = new global::System.Collections.Generic.List<MetaSkillSimpleInfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"sc_63320")]
    public partial class Sc63320 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ret", IsRequired = true)]
        public uint Ret { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(3, Name = @"exp")]
        public uint Exp
        {
            get => __pbn__Exp.GetValueOrDefault();
            set => __pbn__Exp = value;
        }
        public bool ShouldSerializeExp() => __pbn__Exp != null;
        public void ResetExp() => __pbn__Exp = null;
        private uint? __pbn__Exp;

    }

    [global::ProtoBuf.ProtoContract(Name = @"skill_exp")]
    public partial class SkillExp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"skill_id", IsRequired = true)]
        public uint SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"exp", IsRequired = true)]
        public uint Exp { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"skill_info")]
    public partial class SkillInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ship_id", IsRequired = true)]
        public uint ShipId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"skill_id", IsRequired = true)]
        public uint SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"skill_level", IsRequired = true)]
        public uint SkillLevel { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"skill_exp", IsRequired = true)]
        public uint SkillExp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"day_exp", IsRequired = true)]
        public uint DayExp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"add_exp", IsRequired = true)]
        public uint AddExp { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"technologycatchup")]
    public partial class Technologycatchup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version", IsRequired = true)]
        public uint Version { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target", IsRequired = true)]
        public uint Target { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"pursuings")]
        public global::System.Collections.Generic.List<Techpursuing> Pursuings { get; set; } = new global::System.Collections.Generic.List<Techpursuing>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"technologydrop")]
    public partial class Technologydrop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common_list")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> CommonLists { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"drop_list")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> DropLists { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"catchup_list")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> CatchupLists { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"catchupact_list")]
        public global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo> CatchupactLists { get; set; } = new global::System.Collections.Generic.List<global::BLHX.Server.Common.Proto.common.Dropinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"technologyinfo")]
    public partial class Technologyinfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time", IsRequired = true)]
        public uint Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"technologyrefresh")]
    public partial class Technologyrefresh : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target", IsRequired = true)]
        public uint Target { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"technologys")]
        public global::System.Collections.Generic.List<Technologyinfo> Technologys { get; set; } = new global::System.Collections.Generic.List<Technologyinfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"techpursuing")]
    public partial class Techpursuing : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version", IsRequired = true)]
        public uint Version { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"number", IsRequired = true)]
        public uint Number { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"dr_numbers")]
        public global::System.Collections.Generic.List<DrNumber> DrNumbers { get; set; } = new global::System.Collections.Generic.List<DrNumber>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
